// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public interface BridgeMPPRequestStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bridgempp.BridgeMPPRequestStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .bridgempp.RequestStatus requestStatus = 1;</code>
   */
  int getRequestStatusValue();
  /**
   * <code>optional .bridgempp.RequestStatus requestStatus = 1;</code>
   */
  bridgempp.services.socket.protobuf.RequestStatus getRequestStatus();
}
