// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public final class BridgeProtoBuf {
  private BridgeProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bridgempp_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bridgempp_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bridgempp_Endpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bridgempp_Endpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bridgempp_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bridgempp_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bridgempp_Service_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bridgempp_Service_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bridgempp_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bridgempp_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bridgempp_MessageBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bridgempp_MessageBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017bridgempp.proto\022\tbridgempp\"\326\001\n\007Message" +
      "\022\037\n\006sender\030\001 \001(\0132\017.bridgempp.User\022#\n\006ori" +
      "gin\030\002 \001(\0132\023.bridgempp.Endpoint\022)\n\014destin" +
      "ations\030\003 \003(\0132\023.bridgempp.Endpoint\022+\n\021des" +
      "tinationGroups\030\004 \003(\0132\020.bridgempp.Group\022-" +
      "\n\rmessageBodies\030\005 \003(\0132\026.bridgempp.Messag" +
      "eBody\"C\n\010Endpoint\022\022\n\nidentifier\030\001 \001(\t\022#\n" +
      "\007service\030\002 \001(\0132\022.bridgempp.Service\"(\n\004Us" +
      "er\022\022\n\nidentifier\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"\035\n\007" +
      "Service\022\022\n\nidentifier\030\001 \001(\005\"\025\n\005Group\022\014\n\004",
      "name\030\001 \001(\t\"\233\001\n\013MessageBody\0227\n\013messageTyp" +
      "e\030\001 \001(\0162\".bridgempp.MessageBody.MessageT" +
      "ype\022\020\n\010contents\030\002 \001(\t\"A\n\013MessageType\022\016\n\n" +
      "PLAIN_TEXT\020\000\022\010\n\004HTML\020\001\022\t\n\005XHTML\020\002\022\r\n\tIMA" +
      "GE_URL\020\0032\235\001\n\025BridgeMPPDataResolver\022@\n\024Ge" +
      "tUsersFromEndpoint\022\023.bridgempp.Endpoint\032" +
      "\017.bridgempp.User\"\0000\001\022B\n\025GetEndpointsFrom" +
      "Group\022\020.bridgempp.Group\032\023.bridgempp.Endp" +
      "oint\"\0000\001B6\n\"bridgempp.services.socket.pr" +
      "otobufB\016BridgeProtoBufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bridgempp_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bridgempp_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bridgempp_Message_descriptor,
        new java.lang.String[] { "Sender", "Origin", "Destinations", "DestinationGroups", "MessageBodies", });
    internal_static_bridgempp_Endpoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bridgempp_Endpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bridgempp_Endpoint_descriptor,
        new java.lang.String[] { "Identifier", "Service", });
    internal_static_bridgempp_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bridgempp_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bridgempp_User_descriptor,
        new java.lang.String[] { "Identifier", "Name", });
    internal_static_bridgempp_Service_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bridgempp_Service_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bridgempp_Service_descriptor,
        new java.lang.String[] { "Identifier", });
    internal_static_bridgempp_Group_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bridgempp_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bridgempp_Group_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_bridgempp_MessageBody_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bridgempp_MessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bridgempp_MessageBody_descriptor,
        new java.lang.String[] { "MessageType", "Contents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
