// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public interface EndpointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bridgempp.Endpoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>optional string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <code>optional .bridgempp.Service service = 2;</code>
   */
  boolean hasService();
  /**
   * <code>optional .bridgempp.Service service = 2;</code>
   */
  bridgempp.services.socket.protobuf.Service getService();
  /**
   * <code>optional .bridgempp.Service service = 2;</code>
   */
  bridgempp.services.socket.protobuf.ServiceOrBuilder getServiceOrBuilder();
}
