// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public interface MessageTypeSelectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bridgempp.MessageTypeSelection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  java.util.List<bridgempp.services.socket.protobuf.MessageType> getMessageTypeList();
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  int getMessageTypeCount();
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  bridgempp.services.socket.protobuf.MessageType getMessageType(int index);
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getMessageTypeValueList();
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  int getMessageTypeValue(int index);
}
