// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

/**
 * Protobuf type {@code bridgempp.MessageTypeSelection}
 */
public  final class MessageTypeSelection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bridgempp.MessageTypeSelection)
    MessageTypeSelectionOrBuilder {
  // Use MessageTypeSelection.newBuilder() to construct.
  private MessageTypeSelection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageTypeSelection() {
    messageType_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MessageTypeSelection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              messageType_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            messageType_.add(rawValue);
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messageType_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              messageType_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        messageType_ = java.util.Collections.unmodifiableList(messageType_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_MessageTypeSelection_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_MessageTypeSelection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bridgempp.services.socket.protobuf.MessageTypeSelection.class, bridgempp.services.socket.protobuf.MessageTypeSelection.Builder.class);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> messageType_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, bridgempp.services.socket.protobuf.MessageType> messageType_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, bridgempp.services.socket.protobuf.MessageType>() {
            public bridgempp.services.socket.protobuf.MessageType convert(java.lang.Integer from) {
              bridgempp.services.socket.protobuf.MessageType result = bridgempp.services.socket.protobuf.MessageType.valueOf(from);
              return result == null ? bridgempp.services.socket.protobuf.MessageType.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  public java.util.List<bridgempp.services.socket.protobuf.MessageType> getMessageTypeList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, bridgempp.services.socket.protobuf.MessageType>(messageType_, messageType_converter_);
  }
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  public int getMessageTypeCount() {
    return messageType_.size();
  }
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  public bridgempp.services.socket.protobuf.MessageType getMessageType(int index) {
    return messageType_converter_.convert(messageType_.get(index));
  }
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  public java.util.List<java.lang.Integer>
  getMessageTypeValueList() {
    return messageType_;
  }
  /**
   * <code>repeated .bridgempp.MessageType messageType = 1;</code>
   */
  public int getMessageTypeValue(int index) {
    return messageType_.get(index);
  }
  private int messageTypeMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getMessageTypeList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(messageTypeMemoizedSerializedSize);
    }
    for (int i = 0; i < messageType_.size(); i++) {
      output.writeEnumNoTag(messageType_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < messageType_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(messageType_.get(i));
      }
      size += dataSize;
      if (!getMessageTypeList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }messageTypeMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bridgempp.services.socket.protobuf.MessageTypeSelection)) {
      return super.equals(obj);
    }
    bridgempp.services.socket.protobuf.MessageTypeSelection other = (bridgempp.services.socket.protobuf.MessageTypeSelection) obj;

    boolean result = true;
    result = result && messageType_.equals(other.messageType_);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getMessageTypeCount() > 0) {
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bridgempp.services.socket.protobuf.MessageTypeSelection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bridgempp.services.socket.protobuf.MessageTypeSelection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bridgempp.MessageTypeSelection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bridgempp.MessageTypeSelection)
      bridgempp.services.socket.protobuf.MessageTypeSelectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_MessageTypeSelection_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_MessageTypeSelection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bridgempp.services.socket.protobuf.MessageTypeSelection.class, bridgempp.services.socket.protobuf.MessageTypeSelection.Builder.class);
    }

    // Construct using bridgempp.services.socket.protobuf.MessageTypeSelection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      messageType_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_MessageTypeSelection_descriptor;
    }

    public bridgempp.services.socket.protobuf.MessageTypeSelection getDefaultInstanceForType() {
      return bridgempp.services.socket.protobuf.MessageTypeSelection.getDefaultInstance();
    }

    public bridgempp.services.socket.protobuf.MessageTypeSelection build() {
      bridgempp.services.socket.protobuf.MessageTypeSelection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bridgempp.services.socket.protobuf.MessageTypeSelection buildPartial() {
      bridgempp.services.socket.protobuf.MessageTypeSelection result = new bridgempp.services.socket.protobuf.MessageTypeSelection(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        messageType_ = java.util.Collections.unmodifiableList(messageType_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.messageType_ = messageType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bridgempp.services.socket.protobuf.MessageTypeSelection) {
        return mergeFrom((bridgempp.services.socket.protobuf.MessageTypeSelection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bridgempp.services.socket.protobuf.MessageTypeSelection other) {
      if (other == bridgempp.services.socket.protobuf.MessageTypeSelection.getDefaultInstance()) return this;
      if (!other.messageType_.isEmpty()) {
        if (messageType_.isEmpty()) {
          messageType_ = other.messageType_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMessageTypeIsMutable();
          messageType_.addAll(other.messageType_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bridgempp.services.socket.protobuf.MessageTypeSelection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bridgempp.services.socket.protobuf.MessageTypeSelection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> messageType_ =
      java.util.Collections.emptyList();
    private void ensureMessageTypeIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        messageType_ = new java.util.ArrayList<java.lang.Integer>(messageType_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.MessageType> getMessageTypeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, bridgempp.services.socket.protobuf.MessageType>(messageType_, messageType_converter_);
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public int getMessageTypeCount() {
      return messageType_.size();
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public bridgempp.services.socket.protobuf.MessageType getMessageType(int index) {
      return messageType_converter_.convert(messageType_.get(index));
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder setMessageType(
        int index, bridgempp.services.socket.protobuf.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMessageTypeIsMutable();
      messageType_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder addMessageType(bridgempp.services.socket.protobuf.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMessageTypeIsMutable();
      messageType_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder addAllMessageType(
        java.lang.Iterable<? extends bridgempp.services.socket.protobuf.MessageType> values) {
      ensureMessageTypeIsMutable();
      for (bridgempp.services.socket.protobuf.MessageType value : values) {
        messageType_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder clearMessageType() {
      messageType_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public java.util.List<java.lang.Integer>
    getMessageTypeValueList() {
      return java.util.Collections.unmodifiableList(messageType_);
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public int getMessageTypeValue(int index) {
      return messageType_.get(index);
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder setMessageTypeValue(
        int index, int value) {
      ensureMessageTypeIsMutable();
      messageType_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder addMessageTypeValue(int value) {
      ensureMessageTypeIsMutable();
      messageType_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageType messageType = 1;</code>
     */
    public Builder addAllMessageTypeValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureMessageTypeIsMutable();
      for (int value : values) {
        messageType_.add(value);
      }
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:bridgempp.MessageTypeSelection)
  }

  // @@protoc_insertion_point(class_scope:bridgempp.MessageTypeSelection)
  private static final bridgempp.services.socket.protobuf.MessageTypeSelection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bridgempp.services.socket.protobuf.MessageTypeSelection();
  }

  public static bridgempp.services.socket.protobuf.MessageTypeSelection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageTypeSelection>
      PARSER = new com.google.protobuf.AbstractParser<MessageTypeSelection>() {
    public MessageTypeSelection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageTypeSelection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageTypeSelection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageTypeSelection> getParserForType() {
    return PARSER;
  }

  public bridgempp.services.socket.protobuf.MessageTypeSelection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

