// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

/**
 * Protobuf enum {@code bridgempp.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLAIN_TEXT = 0;</code>
   */
  PLAIN_TEXT(0),
  /**
   * <code>HTML = 1;</code>
   */
  HTML(1),
  /**
   * <code>XHTML = 2;</code>
   */
  XHTML(2),
  /**
   * <code>XHTMLXMPP = 3;</code>
   */
  XHTMLXMPP(3),
  /**
   * <code>IMAGE_URL = 4;</code>
   */
  IMAGE_URL(4),
  /**
   * <code>IMAGE_INLINE = 5;</code>
   */
  IMAGE_INLINE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PLAIN_TEXT = 0;</code>
   */
  public static final int PLAIN_TEXT_VALUE = 0;
  /**
   * <code>HTML = 1;</code>
   */
  public static final int HTML_VALUE = 1;
  /**
   * <code>XHTML = 2;</code>
   */
  public static final int XHTML_VALUE = 2;
  /**
   * <code>XHTMLXMPP = 3;</code>
   */
  public static final int XHTMLXMPP_VALUE = 3;
  /**
   * <code>IMAGE_URL = 4;</code>
   */
  public static final int IMAGE_URL_VALUE = 4;
  /**
   * <code>IMAGE_INLINE = 5;</code>
   */
  public static final int IMAGE_INLINE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return PLAIN_TEXT;
      case 1: return HTML;
      case 2: return XHTML;
      case 3: return XHTMLXMPP;
      case 4: return IMAGE_URL;
      case 5: return IMAGE_INLINE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return bridgempp.services.socket.protobuf.BridgeProtoBuf.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bridgempp.MessageType)
}

