// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bridgempp.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .bridgempp.User sender = 1;</code>
   */
  boolean hasSender();
  /**
   * <code>optional .bridgempp.User sender = 1;</code>
   */
  bridgempp.services.socket.protobuf.User getSender();
  /**
   * <code>optional .bridgempp.User sender = 1;</code>
   */
  bridgempp.services.socket.protobuf.UserOrBuilder getSenderOrBuilder();

  /**
   * <code>optional .bridgempp.Endpoint origin = 2;</code>
   */
  boolean hasOrigin();
  /**
   * <code>optional .bridgempp.Endpoint origin = 2;</code>
   */
  bridgempp.services.socket.protobuf.Endpoint getOrigin();
  /**
   * <code>optional .bridgempp.Endpoint origin = 2;</code>
   */
  bridgempp.services.socket.protobuf.EndpointOrBuilder getOriginOrBuilder();

  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  java.util.List<bridgempp.services.socket.protobuf.Endpoint> 
      getDestinationsList();
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  bridgempp.services.socket.protobuf.Endpoint getDestinations(int index);
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  int getDestinationsCount();
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  java.util.List<? extends bridgempp.services.socket.protobuf.EndpointOrBuilder> 
      getDestinationsOrBuilderList();
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  bridgempp.services.socket.protobuf.EndpointOrBuilder getDestinationsOrBuilder(
      int index);

  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  java.util.List<bridgempp.services.socket.protobuf.Group> 
      getDestinationGroupsList();
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  bridgempp.services.socket.protobuf.Group getDestinationGroups(int index);
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  int getDestinationGroupsCount();
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  java.util.List<? extends bridgempp.services.socket.protobuf.GroupOrBuilder> 
      getDestinationGroupsOrBuilderList();
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  bridgempp.services.socket.protobuf.GroupOrBuilder getDestinationGroupsOrBuilder(
      int index);

  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  java.util.List<bridgempp.services.socket.protobuf.MessageBody> 
      getMessageBodiesList();
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  bridgempp.services.socket.protobuf.MessageBody getMessageBodies(int index);
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  int getMessageBodiesCount();
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  java.util.List<? extends bridgempp.services.socket.protobuf.MessageBodyOrBuilder> 
      getMessageBodiesOrBuilderList();
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  bridgempp.services.socket.protobuf.MessageBodyOrBuilder getMessageBodiesOrBuilder(
      int index);
}
