// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

/**
 * Protobuf type {@code bridgempp.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bridgempp.Message)
    MessageOrBuilder {
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    destinations_ = java.util.Collections.emptyList();
    destinationGroups_ = java.util.Collections.emptyList();
    messageBodies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bridgempp.services.socket.protobuf.User.Builder subBuilder = null;
            if (sender_ != null) {
              subBuilder = sender_.toBuilder();
            }
            sender_ = input.readMessage(bridgempp.services.socket.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sender_);
              sender_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            bridgempp.services.socket.protobuf.Endpoint.Builder subBuilder = null;
            if (origin_ != null) {
              subBuilder = origin_.toBuilder();
            }
            origin_ = input.readMessage(bridgempp.services.socket.protobuf.Endpoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(origin_);
              origin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              destinations_ = new java.util.ArrayList<bridgempp.services.socket.protobuf.Endpoint>();
              mutable_bitField0_ |= 0x00000004;
            }
            destinations_.add(
                input.readMessage(bridgempp.services.socket.protobuf.Endpoint.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              destinationGroups_ = new java.util.ArrayList<bridgempp.services.socket.protobuf.Group>();
              mutable_bitField0_ |= 0x00000008;
            }
            destinationGroups_.add(
                input.readMessage(bridgempp.services.socket.protobuf.Group.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              messageBodies_ = new java.util.ArrayList<bridgempp.services.socket.protobuf.MessageBody>();
              mutable_bitField0_ |= 0x00000010;
            }
            messageBodies_.add(
                input.readMessage(bridgempp.services.socket.protobuf.MessageBody.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        destinations_ = java.util.Collections.unmodifiableList(destinations_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        destinationGroups_ = java.util.Collections.unmodifiableList(destinationGroups_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        messageBodies_ = java.util.Collections.unmodifiableList(messageBodies_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_Message_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bridgempp.services.socket.protobuf.Message.class, bridgempp.services.socket.protobuf.Message.Builder.class);
  }

  @SuppressWarnings("unused")
private int bitField0_;
  public static final int SENDER_FIELD_NUMBER = 1;
  private bridgempp.services.socket.protobuf.User sender_;
  /**
   * <code>optional .bridgempp.User sender = 1;</code>
   */
  public boolean hasSender() {
    return sender_ != null;
  }
  /**
   * <code>optional .bridgempp.User sender = 1;</code>
   */
  public bridgempp.services.socket.protobuf.User getSender() {
    return sender_ == null ? bridgempp.services.socket.protobuf.User.getDefaultInstance() : sender_;
  }
  /**
   * <code>optional .bridgempp.User sender = 1;</code>
   */
  public bridgempp.services.socket.protobuf.UserOrBuilder getSenderOrBuilder() {
    return getSender();
  }

  public static final int ORIGIN_FIELD_NUMBER = 2;
  private bridgempp.services.socket.protobuf.Endpoint origin_;
  /**
   * <code>optional .bridgempp.Endpoint origin = 2;</code>
   */
  public boolean hasOrigin() {
    return origin_ != null;
  }
  /**
   * <code>optional .bridgempp.Endpoint origin = 2;</code>
   */
  public bridgempp.services.socket.protobuf.Endpoint getOrigin() {
    return origin_ == null ? bridgempp.services.socket.protobuf.Endpoint.getDefaultInstance() : origin_;
  }
  /**
   * <code>optional .bridgempp.Endpoint origin = 2;</code>
   */
  public bridgempp.services.socket.protobuf.EndpointOrBuilder getOriginOrBuilder() {
    return getOrigin();
  }

  public static final int DESTINATIONS_FIELD_NUMBER = 3;
  private java.util.List<bridgempp.services.socket.protobuf.Endpoint> destinations_;
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  public java.util.List<bridgempp.services.socket.protobuf.Endpoint> getDestinationsList() {
    return destinations_;
  }
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  public java.util.List<? extends bridgempp.services.socket.protobuf.EndpointOrBuilder> 
      getDestinationsOrBuilderList() {
    return destinations_;
  }
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  public int getDestinationsCount() {
    return destinations_.size();
  }
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  public bridgempp.services.socket.protobuf.Endpoint getDestinations(int index) {
    return destinations_.get(index);
  }
  /**
   * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
   */
  public bridgempp.services.socket.protobuf.EndpointOrBuilder getDestinationsOrBuilder(
      int index) {
    return destinations_.get(index);
  }

  public static final int DESTINATIONGROUPS_FIELD_NUMBER = 4;
  private java.util.List<bridgempp.services.socket.protobuf.Group> destinationGroups_;
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  public java.util.List<bridgempp.services.socket.protobuf.Group> getDestinationGroupsList() {
    return destinationGroups_;
  }
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  public java.util.List<? extends bridgempp.services.socket.protobuf.GroupOrBuilder> 
      getDestinationGroupsOrBuilderList() {
    return destinationGroups_;
  }
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  public int getDestinationGroupsCount() {
    return destinationGroups_.size();
  }
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  public bridgempp.services.socket.protobuf.Group getDestinationGroups(int index) {
    return destinationGroups_.get(index);
  }
  /**
   * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
   */
  public bridgempp.services.socket.protobuf.GroupOrBuilder getDestinationGroupsOrBuilder(
      int index) {
    return destinationGroups_.get(index);
  }

  public static final int MESSAGEBODIES_FIELD_NUMBER = 5;
  private java.util.List<bridgempp.services.socket.protobuf.MessageBody> messageBodies_;
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  public java.util.List<bridgempp.services.socket.protobuf.MessageBody> getMessageBodiesList() {
    return messageBodies_;
  }
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  public java.util.List<? extends bridgempp.services.socket.protobuf.MessageBodyOrBuilder> 
      getMessageBodiesOrBuilderList() {
    return messageBodies_;
  }
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  public int getMessageBodiesCount() {
    return messageBodies_.size();
  }
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  public bridgempp.services.socket.protobuf.MessageBody getMessageBodies(int index) {
    return messageBodies_.get(index);
  }
  /**
   * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
   */
  public bridgempp.services.socket.protobuf.MessageBodyOrBuilder getMessageBodiesOrBuilder(
      int index) {
    return messageBodies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sender_ != null) {
      output.writeMessage(1, getSender());
    }
    if (origin_ != null) {
      output.writeMessage(2, getOrigin());
    }
    for (int i = 0; i < destinations_.size(); i++) {
      output.writeMessage(3, destinations_.get(i));
    }
    for (int i = 0; i < destinationGroups_.size(); i++) {
      output.writeMessage(4, destinationGroups_.get(i));
    }
    for (int i = 0; i < messageBodies_.size(); i++) {
      output.writeMessage(5, messageBodies_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sender_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSender());
    }
    if (origin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOrigin());
    }
    for (int i = 0; i < destinations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, destinations_.get(i));
    }
    for (int i = 0; i < destinationGroups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, destinationGroups_.get(i));
    }
    for (int i = 0; i < messageBodies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, messageBodies_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bridgempp.services.socket.protobuf.Message)) {
      return super.equals(obj);
    }
    bridgempp.services.socket.protobuf.Message other = (bridgempp.services.socket.protobuf.Message) obj;

    boolean result = true;
    result = result && (hasSender() == other.hasSender());
    if (hasSender()) {
      result = result && getSender()
          .equals(other.getSender());
    }
    result = result && (hasOrigin() == other.hasOrigin());
    if (hasOrigin()) {
      result = result && getOrigin()
          .equals(other.getOrigin());
    }
    result = result && getDestinationsList()
        .equals(other.getDestinationsList());
    result = result && getDestinationGroupsList()
        .equals(other.getDestinationGroupsList());
    result = result && getMessageBodiesList()
        .equals(other.getMessageBodiesList());
    return result;
  }

  @SuppressWarnings("unchecked")
@java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasSender()) {
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
    }
    if (hasOrigin()) {
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin().hashCode();
    }
    if (getDestinationsCount() > 0) {
      hash = (37 * hash) + DESTINATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationsList().hashCode();
    }
    if (getDestinationGroupsCount() > 0) {
      hash = (37 * hash) + DESTINATIONGROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationGroupsList().hashCode();
    }
    if (getMessageBodiesCount() > 0) {
      hash = (37 * hash) + MESSAGEBODIES_FIELD_NUMBER;
      hash = (53 * hash) + getMessageBodiesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bridgempp.services.socket.protobuf.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bridgempp.services.socket.protobuf.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bridgempp.services.socket.protobuf.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bridgempp.services.socket.protobuf.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bridgempp.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bridgempp.Message)
      bridgempp.services.socket.protobuf.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bridgempp.services.socket.protobuf.Message.class, bridgempp.services.socket.protobuf.Message.Builder.class);
    }

    // Construct using bridgempp.services.socket.protobuf.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDestinationsFieldBuilder();
        getDestinationGroupsFieldBuilder();
        getMessageBodiesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (senderBuilder_ == null) {
        sender_ = null;
      } else {
        sender_ = null;
        senderBuilder_ = null;
      }
      if (originBuilder_ == null) {
        origin_ = null;
      } else {
        origin_ = null;
        originBuilder_ = null;
      }
      if (destinationsBuilder_ == null) {
        destinations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        destinationsBuilder_.clear();
      }
      if (destinationGroupsBuilder_ == null) {
        destinationGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        destinationGroupsBuilder_.clear();
      }
      if (messageBodiesBuilder_ == null) {
        messageBodies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        messageBodiesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bridgempp.services.socket.protobuf.BridgeProtoBuf.internal_static_bridgempp_Message_descriptor;
    }

    public bridgempp.services.socket.protobuf.Message getDefaultInstanceForType() {
      return bridgempp.services.socket.protobuf.Message.getDefaultInstance();
    }

    public bridgempp.services.socket.protobuf.Message build() {
      bridgempp.services.socket.protobuf.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @SuppressWarnings("unused")
	public bridgempp.services.socket.protobuf.Message buildPartial() {
      bridgempp.services.socket.protobuf.Message result = new bridgempp.services.socket.protobuf.Message(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (senderBuilder_ == null) {
        result.sender_ = sender_;
      } else {
        result.sender_ = senderBuilder_.build();
      }
      if (originBuilder_ == null) {
        result.origin_ = origin_;
      } else {
        result.origin_ = originBuilder_.build();
      }
      if (destinationsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          destinations_ = java.util.Collections.unmodifiableList(destinations_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.destinations_ = destinations_;
      } else {
        result.destinations_ = destinationsBuilder_.build();
      }
      if (destinationGroupsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          destinationGroups_ = java.util.Collections.unmodifiableList(destinationGroups_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.destinationGroups_ = destinationGroups_;
      } else {
        result.destinationGroups_ = destinationGroupsBuilder_.build();
      }
      if (messageBodiesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          messageBodies_ = java.util.Collections.unmodifiableList(messageBodies_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.messageBodies_ = messageBodies_;
      } else {
        result.messageBodies_ = messageBodiesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bridgempp.services.socket.protobuf.Message) {
        return mergeFrom((bridgempp.services.socket.protobuf.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bridgempp.services.socket.protobuf.Message other) {
      if (other == bridgempp.services.socket.protobuf.Message.getDefaultInstance()) return this;
      if (other.hasSender()) {
        mergeSender(other.getSender());
      }
      if (other.hasOrigin()) {
        mergeOrigin(other.getOrigin());
      }
      if (destinationsBuilder_ == null) {
        if (!other.destinations_.isEmpty()) {
          if (destinations_.isEmpty()) {
            destinations_ = other.destinations_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDestinationsIsMutable();
            destinations_.addAll(other.destinations_);
          }
          onChanged();
        }
      } else {
        if (!other.destinations_.isEmpty()) {
          if (destinationsBuilder_.isEmpty()) {
            destinationsBuilder_.dispose();
            destinationsBuilder_ = null;
            destinations_ = other.destinations_;
            bitField0_ = (bitField0_ & ~0x00000004);
            destinationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDestinationsFieldBuilder() : null;
          } else {
            destinationsBuilder_.addAllMessages(other.destinations_);
          }
        }
      }
      if (destinationGroupsBuilder_ == null) {
        if (!other.destinationGroups_.isEmpty()) {
          if (destinationGroups_.isEmpty()) {
            destinationGroups_ = other.destinationGroups_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDestinationGroupsIsMutable();
            destinationGroups_.addAll(other.destinationGroups_);
          }
          onChanged();
        }
      } else {
        if (!other.destinationGroups_.isEmpty()) {
          if (destinationGroupsBuilder_.isEmpty()) {
            destinationGroupsBuilder_.dispose();
            destinationGroupsBuilder_ = null;
            destinationGroups_ = other.destinationGroups_;
            bitField0_ = (bitField0_ & ~0x00000008);
            destinationGroupsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDestinationGroupsFieldBuilder() : null;
          } else {
            destinationGroupsBuilder_.addAllMessages(other.destinationGroups_);
          }
        }
      }
      if (messageBodiesBuilder_ == null) {
        if (!other.messageBodies_.isEmpty()) {
          if (messageBodies_.isEmpty()) {
            messageBodies_ = other.messageBodies_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureMessageBodiesIsMutable();
            messageBodies_.addAll(other.messageBodies_);
          }
          onChanged();
        }
      } else {
        if (!other.messageBodies_.isEmpty()) {
          if (messageBodiesBuilder_.isEmpty()) {
            messageBodiesBuilder_.dispose();
            messageBodiesBuilder_ = null;
            messageBodies_ = other.messageBodies_;
            bitField0_ = (bitField0_ & ~0x00000010);
            messageBodiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessageBodiesFieldBuilder() : null;
          } else {
            messageBodiesBuilder_.addAllMessages(other.messageBodies_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bridgempp.services.socket.protobuf.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bridgempp.services.socket.protobuf.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private bridgempp.services.socket.protobuf.User sender_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        bridgempp.services.socket.protobuf.User, bridgempp.services.socket.protobuf.User.Builder, bridgempp.services.socket.protobuf.UserOrBuilder> senderBuilder_;
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public boolean hasSender() {
      return senderBuilder_ != null || sender_ != null;
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public bridgempp.services.socket.protobuf.User getSender() {
      if (senderBuilder_ == null) {
        return sender_ == null ? bridgempp.services.socket.protobuf.User.getDefaultInstance() : sender_;
      } else {
        return senderBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public Builder setSender(bridgempp.services.socket.protobuf.User value) {
      if (senderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sender_ = value;
        onChanged();
      } else {
        senderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public Builder setSender(
        bridgempp.services.socket.protobuf.User.Builder builderForValue) {
      if (senderBuilder_ == null) {
        sender_ = builderForValue.build();
        onChanged();
      } else {
        senderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public Builder mergeSender(bridgempp.services.socket.protobuf.User value) {
      if (senderBuilder_ == null) {
        if (sender_ != null) {
          sender_ =
            bridgempp.services.socket.protobuf.User.newBuilder(sender_).mergeFrom(value).buildPartial();
        } else {
          sender_ = value;
        }
        onChanged();
      } else {
        senderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public Builder clearSender() {
      if (senderBuilder_ == null) {
        sender_ = null;
        onChanged();
      } else {
        sender_ = null;
        senderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public bridgempp.services.socket.protobuf.User.Builder getSenderBuilder() {
      
      onChanged();
      return getSenderFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    public bridgempp.services.socket.protobuf.UserOrBuilder getSenderOrBuilder() {
      if (senderBuilder_ != null) {
        return senderBuilder_.getMessageOrBuilder();
      } else {
        return sender_ == null ?
            bridgempp.services.socket.protobuf.User.getDefaultInstance() : sender_;
      }
    }
    /**
     * <code>optional .bridgempp.User sender = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bridgempp.services.socket.protobuf.User, bridgempp.services.socket.protobuf.User.Builder, bridgempp.services.socket.protobuf.UserOrBuilder> 
        getSenderFieldBuilder() {
      if (senderBuilder_ == null) {
        senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bridgempp.services.socket.protobuf.User, bridgempp.services.socket.protobuf.User.Builder, bridgempp.services.socket.protobuf.UserOrBuilder>(
                getSender(),
                getParentForChildren(),
                isClean());
        sender_ = null;
      }
      return senderBuilder_;
    }

    private bridgempp.services.socket.protobuf.Endpoint origin_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        bridgempp.services.socket.protobuf.Endpoint, bridgempp.services.socket.protobuf.Endpoint.Builder, bridgempp.services.socket.protobuf.EndpointOrBuilder> originBuilder_;
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public boolean hasOrigin() {
      return originBuilder_ != null || origin_ != null;
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public bridgempp.services.socket.protobuf.Endpoint getOrigin() {
      if (originBuilder_ == null) {
        return origin_ == null ? bridgempp.services.socket.protobuf.Endpoint.getDefaultInstance() : origin_;
      } else {
        return originBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public Builder setOrigin(bridgempp.services.socket.protobuf.Endpoint value) {
      if (originBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        origin_ = value;
        onChanged();
      } else {
        originBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public Builder setOrigin(
        bridgempp.services.socket.protobuf.Endpoint.Builder builderForValue) {
      if (originBuilder_ == null) {
        origin_ = builderForValue.build();
        onChanged();
      } else {
        originBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public Builder mergeOrigin(bridgempp.services.socket.protobuf.Endpoint value) {
      if (originBuilder_ == null) {
        if (origin_ != null) {
          origin_ =
            bridgempp.services.socket.protobuf.Endpoint.newBuilder(origin_).mergeFrom(value).buildPartial();
        } else {
          origin_ = value;
        }
        onChanged();
      } else {
        originBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public Builder clearOrigin() {
      if (originBuilder_ == null) {
        origin_ = null;
        onChanged();
      } else {
        origin_ = null;
        originBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public bridgempp.services.socket.protobuf.Endpoint.Builder getOriginBuilder() {
      
      onChanged();
      return getOriginFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    public bridgempp.services.socket.protobuf.EndpointOrBuilder getOriginOrBuilder() {
      if (originBuilder_ != null) {
        return originBuilder_.getMessageOrBuilder();
      } else {
        return origin_ == null ?
            bridgempp.services.socket.protobuf.Endpoint.getDefaultInstance() : origin_;
      }
    }
    /**
     * <code>optional .bridgempp.Endpoint origin = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bridgempp.services.socket.protobuf.Endpoint, bridgempp.services.socket.protobuf.Endpoint.Builder, bridgempp.services.socket.protobuf.EndpointOrBuilder> 
        getOriginFieldBuilder() {
      if (originBuilder_ == null) {
        originBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bridgempp.services.socket.protobuf.Endpoint, bridgempp.services.socket.protobuf.Endpoint.Builder, bridgempp.services.socket.protobuf.EndpointOrBuilder>(
                getOrigin(),
                getParentForChildren(),
                isClean());
        origin_ = null;
      }
      return originBuilder_;
    }

    private java.util.List<bridgempp.services.socket.protobuf.Endpoint> destinations_ =
      java.util.Collections.emptyList();
    private void ensureDestinationsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        destinations_ = new java.util.ArrayList<bridgempp.services.socket.protobuf.Endpoint>(destinations_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bridgempp.services.socket.protobuf.Endpoint, bridgempp.services.socket.protobuf.Endpoint.Builder, bridgempp.services.socket.protobuf.EndpointOrBuilder> destinationsBuilder_;

    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.Endpoint> getDestinationsList() {
      if (destinationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(destinations_);
      } else {
        return destinationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public int getDestinationsCount() {
      if (destinationsBuilder_ == null) {
        return destinations_.size();
      } else {
        return destinationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public bridgempp.services.socket.protobuf.Endpoint getDestinations(int index) {
      if (destinationsBuilder_ == null) {
        return destinations_.get(index);
      } else {
        return destinationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder setDestinations(
        int index, bridgempp.services.socket.protobuf.Endpoint value) {
      if (destinationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDestinationsIsMutable();
        destinations_.set(index, value);
        onChanged();
      } else {
        destinationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder setDestinations(
        int index, bridgempp.services.socket.protobuf.Endpoint.Builder builderForValue) {
      if (destinationsBuilder_ == null) {
        ensureDestinationsIsMutable();
        destinations_.set(index, builderForValue.build());
        onChanged();
      } else {
        destinationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder addDestinations(bridgempp.services.socket.protobuf.Endpoint value) {
      if (destinationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDestinationsIsMutable();
        destinations_.add(value);
        onChanged();
      } else {
        destinationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder addDestinations(
        int index, bridgempp.services.socket.protobuf.Endpoint value) {
      if (destinationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDestinationsIsMutable();
        destinations_.add(index, value);
        onChanged();
      } else {
        destinationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder addDestinations(
        bridgempp.services.socket.protobuf.Endpoint.Builder builderForValue) {
      if (destinationsBuilder_ == null) {
        ensureDestinationsIsMutable();
        destinations_.add(builderForValue.build());
        onChanged();
      } else {
        destinationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder addDestinations(
        int index, bridgempp.services.socket.protobuf.Endpoint.Builder builderForValue) {
      if (destinationsBuilder_ == null) {
        ensureDestinationsIsMutable();
        destinations_.add(index, builderForValue.build());
        onChanged();
      } else {
        destinationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder addAllDestinations(
        java.lang.Iterable<? extends bridgempp.services.socket.protobuf.Endpoint> values) {
      if (destinationsBuilder_ == null) {
        ensureDestinationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, destinations_);
        onChanged();
      } else {
        destinationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder clearDestinations() {
      if (destinationsBuilder_ == null) {
        destinations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        destinationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public Builder removeDestinations(int index) {
      if (destinationsBuilder_ == null) {
        ensureDestinationsIsMutable();
        destinations_.remove(index);
        onChanged();
      } else {
        destinationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public bridgempp.services.socket.protobuf.Endpoint.Builder getDestinationsBuilder(
        int index) {
      return getDestinationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public bridgempp.services.socket.protobuf.EndpointOrBuilder getDestinationsOrBuilder(
        int index) {
      if (destinationsBuilder_ == null) {
        return destinations_.get(index);  } else {
        return destinationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public java.util.List<? extends bridgempp.services.socket.protobuf.EndpointOrBuilder> 
         getDestinationsOrBuilderList() {
      if (destinationsBuilder_ != null) {
        return destinationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(destinations_);
      }
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public bridgempp.services.socket.protobuf.Endpoint.Builder addDestinationsBuilder() {
      return getDestinationsFieldBuilder().addBuilder(
          bridgempp.services.socket.protobuf.Endpoint.getDefaultInstance());
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public bridgempp.services.socket.protobuf.Endpoint.Builder addDestinationsBuilder(
        int index) {
      return getDestinationsFieldBuilder().addBuilder(
          index, bridgempp.services.socket.protobuf.Endpoint.getDefaultInstance());
    }
    /**
     * <code>repeated .bridgempp.Endpoint destinations = 3;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.Endpoint.Builder> 
         getDestinationsBuilderList() {
      return getDestinationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bridgempp.services.socket.protobuf.Endpoint, bridgempp.services.socket.protobuf.Endpoint.Builder, bridgempp.services.socket.protobuf.EndpointOrBuilder> 
        getDestinationsFieldBuilder() {
      if (destinationsBuilder_ == null) {
        destinationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bridgempp.services.socket.protobuf.Endpoint, bridgempp.services.socket.protobuf.Endpoint.Builder, bridgempp.services.socket.protobuf.EndpointOrBuilder>(
                destinations_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        destinations_ = null;
      }
      return destinationsBuilder_;
    }

    private java.util.List<bridgempp.services.socket.protobuf.Group> destinationGroups_ =
      java.util.Collections.emptyList();
    private void ensureDestinationGroupsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        destinationGroups_ = new java.util.ArrayList<bridgempp.services.socket.protobuf.Group>(destinationGroups_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bridgempp.services.socket.protobuf.Group, bridgempp.services.socket.protobuf.Group.Builder, bridgempp.services.socket.protobuf.GroupOrBuilder> destinationGroupsBuilder_;

    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.Group> getDestinationGroupsList() {
      if (destinationGroupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(destinationGroups_);
      } else {
        return destinationGroupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public int getDestinationGroupsCount() {
      if (destinationGroupsBuilder_ == null) {
        return destinationGroups_.size();
      } else {
        return destinationGroupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public bridgempp.services.socket.protobuf.Group getDestinationGroups(int index) {
      if (destinationGroupsBuilder_ == null) {
        return destinationGroups_.get(index);
      } else {
        return destinationGroupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder setDestinationGroups(
        int index, bridgempp.services.socket.protobuf.Group value) {
      if (destinationGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDestinationGroupsIsMutable();
        destinationGroups_.set(index, value);
        onChanged();
      } else {
        destinationGroupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder setDestinationGroups(
        int index, bridgempp.services.socket.protobuf.Group.Builder builderForValue) {
      if (destinationGroupsBuilder_ == null) {
        ensureDestinationGroupsIsMutable();
        destinationGroups_.set(index, builderForValue.build());
        onChanged();
      } else {
        destinationGroupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder addDestinationGroups(bridgempp.services.socket.protobuf.Group value) {
      if (destinationGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDestinationGroupsIsMutable();
        destinationGroups_.add(value);
        onChanged();
      } else {
        destinationGroupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder addDestinationGroups(
        int index, bridgempp.services.socket.protobuf.Group value) {
      if (destinationGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDestinationGroupsIsMutable();
        destinationGroups_.add(index, value);
        onChanged();
      } else {
        destinationGroupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder addDestinationGroups(
        bridgempp.services.socket.protobuf.Group.Builder builderForValue) {
      if (destinationGroupsBuilder_ == null) {
        ensureDestinationGroupsIsMutable();
        destinationGroups_.add(builderForValue.build());
        onChanged();
      } else {
        destinationGroupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder addDestinationGroups(
        int index, bridgempp.services.socket.protobuf.Group.Builder builderForValue) {
      if (destinationGroupsBuilder_ == null) {
        ensureDestinationGroupsIsMutable();
        destinationGroups_.add(index, builderForValue.build());
        onChanged();
      } else {
        destinationGroupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder addAllDestinationGroups(
        java.lang.Iterable<? extends bridgempp.services.socket.protobuf.Group> values) {
      if (destinationGroupsBuilder_ == null) {
        ensureDestinationGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, destinationGroups_);
        onChanged();
      } else {
        destinationGroupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder clearDestinationGroups() {
      if (destinationGroupsBuilder_ == null) {
        destinationGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        destinationGroupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public Builder removeDestinationGroups(int index) {
      if (destinationGroupsBuilder_ == null) {
        ensureDestinationGroupsIsMutable();
        destinationGroups_.remove(index);
        onChanged();
      } else {
        destinationGroupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public bridgempp.services.socket.protobuf.Group.Builder getDestinationGroupsBuilder(
        int index) {
      return getDestinationGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public bridgempp.services.socket.protobuf.GroupOrBuilder getDestinationGroupsOrBuilder(
        int index) {
      if (destinationGroupsBuilder_ == null) {
        return destinationGroups_.get(index);  } else {
        return destinationGroupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public java.util.List<? extends bridgempp.services.socket.protobuf.GroupOrBuilder> 
         getDestinationGroupsOrBuilderList() {
      if (destinationGroupsBuilder_ != null) {
        return destinationGroupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(destinationGroups_);
      }
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public bridgempp.services.socket.protobuf.Group.Builder addDestinationGroupsBuilder() {
      return getDestinationGroupsFieldBuilder().addBuilder(
          bridgempp.services.socket.protobuf.Group.getDefaultInstance());
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public bridgempp.services.socket.protobuf.Group.Builder addDestinationGroupsBuilder(
        int index) {
      return getDestinationGroupsFieldBuilder().addBuilder(
          index, bridgempp.services.socket.protobuf.Group.getDefaultInstance());
    }
    /**
     * <code>repeated .bridgempp.Group destinationGroups = 4;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.Group.Builder> 
         getDestinationGroupsBuilderList() {
      return getDestinationGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bridgempp.services.socket.protobuf.Group, bridgempp.services.socket.protobuf.Group.Builder, bridgempp.services.socket.protobuf.GroupOrBuilder> 
        getDestinationGroupsFieldBuilder() {
      if (destinationGroupsBuilder_ == null) {
        destinationGroupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bridgempp.services.socket.protobuf.Group, bridgempp.services.socket.protobuf.Group.Builder, bridgempp.services.socket.protobuf.GroupOrBuilder>(
                destinationGroups_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        destinationGroups_ = null;
      }
      return destinationGroupsBuilder_;
    }

    private java.util.List<bridgempp.services.socket.protobuf.MessageBody> messageBodies_ =
      java.util.Collections.emptyList();
    private void ensureMessageBodiesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        messageBodies_ = new java.util.ArrayList<bridgempp.services.socket.protobuf.MessageBody>(messageBodies_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bridgempp.services.socket.protobuf.MessageBody, bridgempp.services.socket.protobuf.MessageBody.Builder, bridgempp.services.socket.protobuf.MessageBodyOrBuilder> messageBodiesBuilder_;

    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.MessageBody> getMessageBodiesList() {
      if (messageBodiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messageBodies_);
      } else {
        return messageBodiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public int getMessageBodiesCount() {
      if (messageBodiesBuilder_ == null) {
        return messageBodies_.size();
      } else {
        return messageBodiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public bridgempp.services.socket.protobuf.MessageBody getMessageBodies(int index) {
      if (messageBodiesBuilder_ == null) {
        return messageBodies_.get(index);
      } else {
        return messageBodiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder setMessageBodies(
        int index, bridgempp.services.socket.protobuf.MessageBody value) {
      if (messageBodiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageBodiesIsMutable();
        messageBodies_.set(index, value);
        onChanged();
      } else {
        messageBodiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder setMessageBodies(
        int index, bridgempp.services.socket.protobuf.MessageBody.Builder builderForValue) {
      if (messageBodiesBuilder_ == null) {
        ensureMessageBodiesIsMutable();
        messageBodies_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageBodiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder addMessageBodies(bridgempp.services.socket.protobuf.MessageBody value) {
      if (messageBodiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageBodiesIsMutable();
        messageBodies_.add(value);
        onChanged();
      } else {
        messageBodiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder addMessageBodies(
        int index, bridgempp.services.socket.protobuf.MessageBody value) {
      if (messageBodiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageBodiesIsMutable();
        messageBodies_.add(index, value);
        onChanged();
      } else {
        messageBodiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder addMessageBodies(
        bridgempp.services.socket.protobuf.MessageBody.Builder builderForValue) {
      if (messageBodiesBuilder_ == null) {
        ensureMessageBodiesIsMutable();
        messageBodies_.add(builderForValue.build());
        onChanged();
      } else {
        messageBodiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder addMessageBodies(
        int index, bridgempp.services.socket.protobuf.MessageBody.Builder builderForValue) {
      if (messageBodiesBuilder_ == null) {
        ensureMessageBodiesIsMutable();
        messageBodies_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageBodiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder addAllMessageBodies(
        java.lang.Iterable<? extends bridgempp.services.socket.protobuf.MessageBody> values) {
      if (messageBodiesBuilder_ == null) {
        ensureMessageBodiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageBodies_);
        onChanged();
      } else {
        messageBodiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder clearMessageBodies() {
      if (messageBodiesBuilder_ == null) {
        messageBodies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        messageBodiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public Builder removeMessageBodies(int index) {
      if (messageBodiesBuilder_ == null) {
        ensureMessageBodiesIsMutable();
        messageBodies_.remove(index);
        onChanged();
      } else {
        messageBodiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public bridgempp.services.socket.protobuf.MessageBody.Builder getMessageBodiesBuilder(
        int index) {
      return getMessageBodiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public bridgempp.services.socket.protobuf.MessageBodyOrBuilder getMessageBodiesOrBuilder(
        int index) {
      if (messageBodiesBuilder_ == null) {
        return messageBodies_.get(index);  } else {
        return messageBodiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public java.util.List<? extends bridgempp.services.socket.protobuf.MessageBodyOrBuilder> 
         getMessageBodiesOrBuilderList() {
      if (messageBodiesBuilder_ != null) {
        return messageBodiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messageBodies_);
      }
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public bridgempp.services.socket.protobuf.MessageBody.Builder addMessageBodiesBuilder() {
      return getMessageBodiesFieldBuilder().addBuilder(
          bridgempp.services.socket.protobuf.MessageBody.getDefaultInstance());
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public bridgempp.services.socket.protobuf.MessageBody.Builder addMessageBodiesBuilder(
        int index) {
      return getMessageBodiesFieldBuilder().addBuilder(
          index, bridgempp.services.socket.protobuf.MessageBody.getDefaultInstance());
    }
    /**
     * <code>repeated .bridgempp.MessageBody messageBodies = 5;</code>
     */
    public java.util.List<bridgempp.services.socket.protobuf.MessageBody.Builder> 
         getMessageBodiesBuilderList() {
      return getMessageBodiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bridgempp.services.socket.protobuf.MessageBody, bridgempp.services.socket.protobuf.MessageBody.Builder, bridgempp.services.socket.protobuf.MessageBodyOrBuilder> 
        getMessageBodiesFieldBuilder() {
      if (messageBodiesBuilder_ == null) {
        messageBodiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bridgempp.services.socket.protobuf.MessageBody, bridgempp.services.socket.protobuf.MessageBody.Builder, bridgempp.services.socket.protobuf.MessageBodyOrBuilder>(
                messageBodies_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        messageBodies_ = null;
      }
      return messageBodiesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:bridgempp.Message)
  }

  // @@protoc_insertion_point(class_scope:bridgempp.Message)
  private static final bridgempp.services.socket.protobuf.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bridgempp.services.socket.protobuf.Message();
  }

  public static bridgempp.services.socket.protobuf.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  public bridgempp.services.socket.protobuf.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

