// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

/**
 * Protobuf enum {@code bridgempp.RequestStatus}
 */
public enum RequestStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <code>FAILED = 1;</code>
   */
  FAILED(1),
  /**
   * <code>FAILED_RETRY = 2;</code>
   */
  FAILED_RETRY(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <code>FAILED = 1;</code>
   */
  public static final int FAILED_VALUE = 1;
  /**
   * <code>FAILED_RETRY = 2;</code>
   */
  public static final int FAILED_RETRY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RequestStatus valueOf(int value) {
    return forNumber(value);
  }

  public static RequestStatus forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return FAILED;
      case 2: return FAILED_RETRY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RequestStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RequestStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RequestStatus>() {
          public RequestStatus findValueByNumber(int number) {
            return RequestStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return bridgempp.services.socket.protobuf.BridgeProtoBuf.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final RequestStatus[] VALUES = values();

  public static RequestStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RequestStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bridgempp.RequestStatus)
}

