// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public interface ServiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bridgempp.Service)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 identifier = 1;</code>
   */
  int getIdentifier();
}
