// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bridgempp.proto

package bridgempp.services.socket.protobuf;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bridgempp.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>optional string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
